#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Onfido",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;

SWIFT_CLASS_NAMED("Appearance")
@interface ONAppearance : NSObject
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("secondaryBackgroundPressedColor will become unavailable.");
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor fontRegular:(NSString * _Nullable)fontRegular fontBold:(NSString * _Nullable)fontBold supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSupportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Onfido25BaseDocumentConfiguration")
@interface BaseDocumentConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS_NAMED("CertificatePinningConfiguration")
@interface ONCertificatePinningConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hashes;
- (nullable instancetype)initWithHashes:(NSArray<NSString *> * _Nonnull)hashes error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM(NSInteger, DocumentFormat, open) {
  DocumentFormatCard = 0,
  DocumentFormatFolded = 1,
};

@class DocumentConfigBuilder;

SWIFT_CLASS_NAMED("DocumentTypeVariantConfig")
@interface ONDocumentTypeVariantConfig : NSObject
+ (DocumentConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class PassportConfiguration;
@class DrivingLicenceConfiguration;
@class NationalIdentityConfiguration;
@class ResidencePermitConfiguration;
@class VisaConfiguration;
@class WorkPermitConfiguration;
@class GenericDocumentConfiguration;

SWIFT_CLASS("_TtCC6Onfido25DocumentTypeVariantConfig21DocumentConfigBuilder")
@interface DocumentConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (DocumentConfigBuilder * _Nonnull)withPassportWithConfig:(PassportConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withDrivingLicenceWithConfig:(DrivingLicenceConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withNationalIdentityCardWithConfig:(NationalIdentityConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withResidencePermitWithConfig:(ResidencePermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withVisaWithConfig:(VisaConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withWorkPermitWithConfig:(WorkPermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withGenericWithConfig:(GenericDocumentConfiguration * _Nullable)config;
- (ONDocumentTypeVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DrivingLicenceConfiguration")
@interface DrivingLicenceConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONEnterpriseFeaturesBuilder;

SWIFT_CLASS_NAMED("EnterpriseFeatures")
@interface ONEnterpriseFeatures : NSObject
- (nonnull instancetype)initWithHideOnfidoLogo:(BOOL)hideOnfidoLogo OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use EnterpriseFeatures.builder().withHideOnfidoLogo(_:).build() instead.");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (ONEnterpriseFeaturesBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("Builder")
@interface ONEnterpriseFeaturesBuilder : NSObject
- (ONEnterpriseFeaturesBuilder * _Nonnull)withHideOnfidoLogo:(BOOL)hideOnfidoLogo;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withCobrandingText:(NSString * _Nonnull)cobrandingText;
- (ONEnterpriseFeatures * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Minimal capture UI for documents and faces with built-in validation
SWIFT_CLASS("_TtC6Onfido5Event")
@interface Event : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull properties;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Builder;

SWIFT_CLASS_NAMED("FaceStepVariantConfig")
@interface ONFaceStepVariantConfig : NSObject
+ (Builder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class VideoStepConfiguration;
@class PhotoStepConfiguration;

SWIFT_CLASS("_TtCC6Onfido21FaceStepVariantConfig7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (Builder * _Nonnull)withVideoCaptureWithConfig:(VideoStepConfiguration * _Nullable)config;
- (Builder * _Nonnull)withPhotoCaptureWithConfig:(PhotoStepConfiguration * _Nullable)config;
- (ONFaceStepVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("GenericDocumentConfiguration")
@interface GenericDocumentConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end






SWIFT_CLASS_NAMED("NationalIdentityConfiguration")
@interface NationalIdentityConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// Address object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONAddressResult")
@interface ONAddressResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable flatNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingName;
@property (nonatomic, readonly, copy) NSString * _Nullable street;
@property (nonatomic, readonly, copy) NSString * _Nullable subStreet;
@property (nonatomic, readonly, copy) NSString * _Nullable town;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSDate * _Nullable startDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class NSDate;
@class NSNumber;

SWIFT_CLASS_NAMED("ONDocumentResult")
@interface ONDocumentResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable side;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFaceResult")
@interface ONFaceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfig;
@class UIViewController;
@class ONFlowResponse;

/// Objective-C wrapper for OnfidoFlow
SWIFT_CLASS_NAMED("ONFlow")
@interface ONFlow : NSObject
- (nonnull instancetype)initWithFlowConfiguration:(ONFlowConfig * _Nonnull)flowConfiguration OBJC_DESIGNATED_INITIALIZER;
- (UIViewController * _Nullable)runAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler dismissFlowOnCompletion:(BOOL)dismissFlowOnCompletion;
- (ONFlow * _Nonnull)withEventHandler:(void (^ _Nonnull)(Event * _Nonnull))eventHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfigBuilder;

/// Objective-C wrapper for OnfidoConfig struct
/// NOTE: Swift structs are not supported in Objective-C
SWIFT_CLASS_NAMED("ONFlowConfig")
@interface ONFlowConfig : NSObject
+ (ONFlowConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFlowConfigBuilder")
@interface ONFlowConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)withToken:(NSString * _Nonnull)token;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken expireHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nonnull)))expireHandler;
- (void)withApplicantId:(NSString * _Nonnull)applicantId;
- (void)withWelcomeStep;
- (void)withDocumentStep;
- (void)withDocumentStepOfType:(ONDocumentTypeVariantConfig * _Nonnull)variant;
- (void)withFaceStepOfVariant:(ONFaceStepVariantConfig * _Nonnull)variant;
- (void)withCustomLocalization;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName in:(NSBundle * _Nonnull)bundle;
- (void)withAppearance:(ONAppearance * _Nonnull)appearance;
- (void)withEnterpriseFeatures:(ONEnterpriseFeatures * _Nonnull)enterpriseFeatures;
- (void)withCertificatePinningConfiguration:(ONCertificatePinningConfiguration * _Nonnull)configuration;
/// Builds ONFlowConfig object
- (ONFlowConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowConfigError, "ONFlowConfigError", open) {
  ONFlowConfigErrorMissingToken = 0,
  ONFlowConfigErrorMissingSteps = 1,
  ONFlowConfigErrorMissingApplicant = 2,
  ONFlowConfigErrorMutlipleTokenTypes = 3,
  ONFlowConfigErrorApplicantProvidedWithSDKToken = 4,
  ONFlowConfigErrorInvalidDocumentFormatAndCountryCombination = 5,
  ONFlowConfigErrorEnterpriseFeaturesNotAuthorized = 6,
  ONFlowConfigErrorSelectedEnterpriseFeatureNotAuthorized = 7,
  ONFlowConfigErrorEnterpriseFeatureProvidedWithMobileToken = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowError, "ONFlowError", open) {
  ONFlowErrorCameraPermission = 0,
  ONFlowErrorMicrophonePermission = 1,
  ONFlowErrorUpload = 2,
  ONFlowErrorException = 3,
  ONFlowErrorFailedToWriteToDisk = 4,
};

@class ONFlowResult;
@class NSError;

SWIFT_CLASS_NAMED("ONFlowResponse")
@interface ONFlowResponse : NSObject
/// The results generated upon a success run of the flow
@property (nonatomic, copy) NSArray<ONFlowResult *> * _Nullable results;
/// The error encountered during the flow if any
@property (nonatomic, strong) NSError * _Nullable error;
/// Boolean value to determine whether the flow was canceled by the user
@property (nonatomic) BOOL userCanceled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ONFlowResultType : NSInteger;

SWIFT_CLASS_NAMED("ONFlowResult")
@interface ONFlowResult : NSObject
/// The type of result
@property (nonatomic, readonly) enum ONFlowResultType type;
/// The result object (ONApplicantResult, ONDocumentResult, ONFaceResult)
@property (nonatomic, strong) id _Nonnull result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// Enumeration to list the possible results type generated during the flow
typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowResultType, "ONFlowResultType", open) {
  ONFlowResultTypeDocument = 0,
  ONFlowResultTypeFace = 1,
};


/// IdNumber object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONIdNumberResult")
@interface ONIdNumberResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSString * _Nullable stateCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PassportConfiguration")
@interface PassportConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("PhotoStepConfiguration")
@interface PhotoStepConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ResidencePermitConfiguration")
@interface ResidencePermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




































SWIFT_CLASS_NAMED("VideoStepConfiguration")
@interface VideoStepConfiguration : NSObject
- (nonnull instancetype)initWithShowIntroVideo:(BOOL)showIntroVideo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VisaConfiguration")
@interface VisaConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WorkPermitConfiguration")
@interface WorkPermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Onfido",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;

SWIFT_CLASS_NAMED("Appearance")
@interface ONAppearance : NSObject
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("secondaryBackgroundPressedColor will become unavailable.");
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor fontRegular:(NSString * _Nullable)fontRegular fontBold:(NSString * _Nullable)fontBold supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSupportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Onfido25BaseDocumentConfiguration")
@interface BaseDocumentConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS_NAMED("CertificatePinningConfiguration")
@interface ONCertificatePinningConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hashes;
- (nullable instancetype)initWithHashes:(NSArray<NSString *> * _Nonnull)hashes error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM(NSInteger, DocumentFormat, open) {
  DocumentFormatCard = 0,
  DocumentFormatFolded = 1,
};

@class DocumentConfigBuilder;

SWIFT_CLASS_NAMED("DocumentTypeVariantConfig")
@interface ONDocumentTypeVariantConfig : NSObject
+ (DocumentConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class PassportConfiguration;
@class DrivingLicenceConfiguration;
@class NationalIdentityConfiguration;
@class ResidencePermitConfiguration;
@class VisaConfiguration;
@class WorkPermitConfiguration;
@class GenericDocumentConfiguration;

SWIFT_CLASS("_TtCC6Onfido25DocumentTypeVariantConfig21DocumentConfigBuilder")
@interface DocumentConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (DocumentConfigBuilder * _Nonnull)withPassportWithConfig:(PassportConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withDrivingLicenceWithConfig:(DrivingLicenceConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withNationalIdentityCardWithConfig:(NationalIdentityConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withResidencePermitWithConfig:(ResidencePermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withVisaWithConfig:(VisaConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withWorkPermitWithConfig:(WorkPermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withGenericWithConfig:(GenericDocumentConfiguration * _Nullable)config;
- (ONDocumentTypeVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DrivingLicenceConfiguration")
@interface DrivingLicenceConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONEnterpriseFeaturesBuilder;

SWIFT_CLASS_NAMED("EnterpriseFeatures")
@interface ONEnterpriseFeatures : NSObject
- (nonnull instancetype)initWithHideOnfidoLogo:(BOOL)hideOnfidoLogo OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use EnterpriseFeatures.builder().withHideOnfidoLogo(_:).build() instead.");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (ONEnterpriseFeaturesBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("Builder")
@interface ONEnterpriseFeaturesBuilder : NSObject
- (ONEnterpriseFeaturesBuilder * _Nonnull)withHideOnfidoLogo:(BOOL)hideOnfidoLogo;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withCobrandingText:(NSString * _Nonnull)cobrandingText;
- (ONEnterpriseFeatures * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Minimal capture UI for documents and faces with built-in validation
SWIFT_CLASS("_TtC6Onfido5Event")
@interface Event : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull properties;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Builder;

SWIFT_CLASS_NAMED("FaceStepVariantConfig")
@interface ONFaceStepVariantConfig : NSObject
+ (Builder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class VideoStepConfiguration;
@class PhotoStepConfiguration;

SWIFT_CLASS("_TtCC6Onfido21FaceStepVariantConfig7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (Builder * _Nonnull)withVideoCaptureWithConfig:(VideoStepConfiguration * _Nullable)config;
- (Builder * _Nonnull)withPhotoCaptureWithConfig:(PhotoStepConfiguration * _Nullable)config;
- (ONFaceStepVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("GenericDocumentConfiguration")
@interface GenericDocumentConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end






SWIFT_CLASS_NAMED("NationalIdentityConfiguration")
@interface NationalIdentityConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// Address object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONAddressResult")
@interface ONAddressResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable flatNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingName;
@property (nonatomic, readonly, copy) NSString * _Nullable street;
@property (nonatomic, readonly, copy) NSString * _Nullable subStreet;
@property (nonatomic, readonly, copy) NSString * _Nullable town;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSDate * _Nullable startDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class NSDate;
@class NSNumber;

SWIFT_CLASS_NAMED("ONDocumentResult")
@interface ONDocumentResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable side;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFaceResult")
@interface ONFaceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfig;
@class UIViewController;
@class ONFlowResponse;

/// Objective-C wrapper for OnfidoFlow
SWIFT_CLASS_NAMED("ONFlow")
@interface ONFlow : NSObject
- (nonnull instancetype)initWithFlowConfiguration:(ONFlowConfig * _Nonnull)flowConfiguration OBJC_DESIGNATED_INITIALIZER;
- (UIViewController * _Nullable)runAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler dismissFlowOnCompletion:(BOOL)dismissFlowOnCompletion;
- (ONFlow * _Nonnull)withEventHandler:(void (^ _Nonnull)(Event * _Nonnull))eventHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfigBuilder;

/// Objective-C wrapper for OnfidoConfig struct
/// NOTE: Swift structs are not supported in Objective-C
SWIFT_CLASS_NAMED("ONFlowConfig")
@interface ONFlowConfig : NSObject
+ (ONFlowConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFlowConfigBuilder")
@interface ONFlowConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)withToken:(NSString * _Nonnull)token;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken expireHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nonnull)))expireHandler;
- (void)withApplicantId:(NSString * _Nonnull)applicantId;
- (void)withWelcomeStep;
- (void)withDocumentStep;
- (void)withDocumentStepOfType:(ONDocumentTypeVariantConfig * _Nonnull)variant;
- (void)withFaceStepOfVariant:(ONFaceStepVariantConfig * _Nonnull)variant;
- (void)withCustomLocalization;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName in:(NSBundle * _Nonnull)bundle;
- (void)withAppearance:(ONAppearance * _Nonnull)appearance;
- (void)withEnterpriseFeatures:(ONEnterpriseFeatures * _Nonnull)enterpriseFeatures;
- (void)withCertificatePinningConfiguration:(ONCertificatePinningConfiguration * _Nonnull)configuration;
/// Builds ONFlowConfig object
- (ONFlowConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowConfigError, "ONFlowConfigError", open) {
  ONFlowConfigErrorMissingToken = 0,
  ONFlowConfigErrorMissingSteps = 1,
  ONFlowConfigErrorMissingApplicant = 2,
  ONFlowConfigErrorMutlipleTokenTypes = 3,
  ONFlowConfigErrorApplicantProvidedWithSDKToken = 4,
  ONFlowConfigErrorInvalidDocumentFormatAndCountryCombination = 5,
  ONFlowConfigErrorEnterpriseFeaturesNotAuthorized = 6,
  ONFlowConfigErrorSelectedEnterpriseFeatureNotAuthorized = 7,
  ONFlowConfigErrorEnterpriseFeatureProvidedWithMobileToken = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowError, "ONFlowError", open) {
  ONFlowErrorCameraPermission = 0,
  ONFlowErrorMicrophonePermission = 1,
  ONFlowErrorUpload = 2,
  ONFlowErrorException = 3,
  ONFlowErrorFailedToWriteToDisk = 4,
};

@class ONFlowResult;
@class NSError;

SWIFT_CLASS_NAMED("ONFlowResponse")
@interface ONFlowResponse : NSObject
/// The results generated upon a success run of the flow
@property (nonatomic, copy) NSArray<ONFlowResult *> * _Nullable results;
/// The error encountered during the flow if any
@property (nonatomic, strong) NSError * _Nullable error;
/// Boolean value to determine whether the flow was canceled by the user
@property (nonatomic) BOOL userCanceled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ONFlowResultType : NSInteger;

SWIFT_CLASS_NAMED("ONFlowResult")
@interface ONFlowResult : NSObject
/// The type of result
@property (nonatomic, readonly) enum ONFlowResultType type;
/// The result object (ONApplicantResult, ONDocumentResult, ONFaceResult)
@property (nonatomic, strong) id _Nonnull result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// Enumeration to list the possible results type generated during the flow
typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowResultType, "ONFlowResultType", open) {
  ONFlowResultTypeDocument = 0,
  ONFlowResultTypeFace = 1,
};


/// IdNumber object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONIdNumberResult")
@interface ONIdNumberResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSString * _Nullable stateCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PassportConfiguration")
@interface PassportConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("PhotoStepConfiguration")
@interface PhotoStepConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ResidencePermitConfiguration")
@interface ResidencePermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




































SWIFT_CLASS_NAMED("VideoStepConfiguration")
@interface VideoStepConfiguration : NSObject
- (nonnull instancetype)initWithShowIntroVideo:(BOOL)showIntroVideo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VisaConfiguration")
@interface VisaConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WorkPermitConfiguration")
@interface WorkPermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Onfido",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;

SWIFT_CLASS_NAMED("Appearance")
@interface ONAppearance : NSObject
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("secondaryBackgroundPressedColor will become unavailable.");
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor fontRegular:(NSString * _Nullable)fontRegular fontBold:(NSString * _Nullable)fontBold supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSupportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Onfido25BaseDocumentConfiguration")
@interface BaseDocumentConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS_NAMED("CertificatePinningConfiguration")
@interface ONCertificatePinningConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hashes;
- (nullable instancetype)initWithHashes:(NSArray<NSString *> * _Nonnull)hashes error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM(NSInteger, DocumentFormat, open) {
  DocumentFormatCard = 0,
  DocumentFormatFolded = 1,
};

@class DocumentConfigBuilder;

SWIFT_CLASS_NAMED("DocumentTypeVariantConfig")
@interface ONDocumentTypeVariantConfig : NSObject
+ (DocumentConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class PassportConfiguration;
@class DrivingLicenceConfiguration;
@class NationalIdentityConfiguration;
@class ResidencePermitConfiguration;
@class VisaConfiguration;
@class WorkPermitConfiguration;
@class GenericDocumentConfiguration;

SWIFT_CLASS("_TtCC6Onfido25DocumentTypeVariantConfig21DocumentConfigBuilder")
@interface DocumentConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (DocumentConfigBuilder * _Nonnull)withPassportWithConfig:(PassportConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withDrivingLicenceWithConfig:(DrivingLicenceConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withNationalIdentityCardWithConfig:(NationalIdentityConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withResidencePermitWithConfig:(ResidencePermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withVisaWithConfig:(VisaConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withWorkPermitWithConfig:(WorkPermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withGenericWithConfig:(GenericDocumentConfiguration * _Nullable)config;
- (ONDocumentTypeVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DrivingLicenceConfiguration")
@interface DrivingLicenceConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONEnterpriseFeaturesBuilder;

SWIFT_CLASS_NAMED("EnterpriseFeatures")
@interface ONEnterpriseFeatures : NSObject
- (nonnull instancetype)initWithHideOnfidoLogo:(BOOL)hideOnfidoLogo OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use EnterpriseFeatures.builder().withHideOnfidoLogo(_:).build() instead.");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (ONEnterpriseFeaturesBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("Builder")
@interface ONEnterpriseFeaturesBuilder : NSObject
- (ONEnterpriseFeaturesBuilder * _Nonnull)withHideOnfidoLogo:(BOOL)hideOnfidoLogo;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withCobrandingText:(NSString * _Nonnull)cobrandingText;
- (ONEnterpriseFeatures * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Minimal capture UI for documents and faces with built-in validation
SWIFT_CLASS("_TtC6Onfido5Event")
@interface Event : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull properties;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Builder;

SWIFT_CLASS_NAMED("FaceStepVariantConfig")
@interface ONFaceStepVariantConfig : NSObject
+ (Builder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class VideoStepConfiguration;
@class PhotoStepConfiguration;

SWIFT_CLASS("_TtCC6Onfido21FaceStepVariantConfig7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (Builder * _Nonnull)withVideoCaptureWithConfig:(VideoStepConfiguration * _Nullable)config;
- (Builder * _Nonnull)withPhotoCaptureWithConfig:(PhotoStepConfiguration * _Nullable)config;
- (ONFaceStepVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("GenericDocumentConfiguration")
@interface GenericDocumentConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end






SWIFT_CLASS_NAMED("NationalIdentityConfiguration")
@interface NationalIdentityConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// Address object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONAddressResult")
@interface ONAddressResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable flatNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingName;
@property (nonatomic, readonly, copy) NSString * _Nullable street;
@property (nonatomic, readonly, copy) NSString * _Nullable subStreet;
@property (nonatomic, readonly, copy) NSString * _Nullable town;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSDate * _Nullable startDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class NSDate;
@class NSNumber;

SWIFT_CLASS_NAMED("ONDocumentResult")
@interface ONDocumentResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable side;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFaceResult")
@interface ONFaceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfig;
@class UIViewController;
@class ONFlowResponse;

/// Objective-C wrapper for OnfidoFlow
SWIFT_CLASS_NAMED("ONFlow")
@interface ONFlow : NSObject
- (nonnull instancetype)initWithFlowConfiguration:(ONFlowConfig * _Nonnull)flowConfiguration OBJC_DESIGNATED_INITIALIZER;
- (UIViewController * _Nullable)runAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler dismissFlowOnCompletion:(BOOL)dismissFlowOnCompletion;
- (ONFlow * _Nonnull)withEventHandler:(void (^ _Nonnull)(Event * _Nonnull))eventHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfigBuilder;

/// Objective-C wrapper for OnfidoConfig struct
/// NOTE: Swift structs are not supported in Objective-C
SWIFT_CLASS_NAMED("ONFlowConfig")
@interface ONFlowConfig : NSObject
+ (ONFlowConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFlowConfigBuilder")
@interface ONFlowConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)withToken:(NSString * _Nonnull)token;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken expireHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nonnull)))expireHandler;
- (void)withApplicantId:(NSString * _Nonnull)applicantId;
- (void)withWelcomeStep;
- (void)withDocumentStep;
- (void)withDocumentStepOfType:(ONDocumentTypeVariantConfig * _Nonnull)variant;
- (void)withFaceStepOfVariant:(ONFaceStepVariantConfig * _Nonnull)variant;
- (void)withCustomLocalization;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName in:(NSBundle * _Nonnull)bundle;
- (void)withAppearance:(ONAppearance * _Nonnull)appearance;
- (void)withEnterpriseFeatures:(ONEnterpriseFeatures * _Nonnull)enterpriseFeatures;
- (void)withCertificatePinningConfiguration:(ONCertificatePinningConfiguration * _Nonnull)configuration;
/// Builds ONFlowConfig object
- (ONFlowConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowConfigError, "ONFlowConfigError", open) {
  ONFlowConfigErrorMissingToken = 0,
  ONFlowConfigErrorMissingSteps = 1,
  ONFlowConfigErrorMissingApplicant = 2,
  ONFlowConfigErrorMutlipleTokenTypes = 3,
  ONFlowConfigErrorApplicantProvidedWithSDKToken = 4,
  ONFlowConfigErrorInvalidDocumentFormatAndCountryCombination = 5,
  ONFlowConfigErrorEnterpriseFeaturesNotAuthorized = 6,
  ONFlowConfigErrorSelectedEnterpriseFeatureNotAuthorized = 7,
  ONFlowConfigErrorEnterpriseFeatureProvidedWithMobileToken = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowError, "ONFlowError", open) {
  ONFlowErrorCameraPermission = 0,
  ONFlowErrorMicrophonePermission = 1,
  ONFlowErrorUpload = 2,
  ONFlowErrorException = 3,
  ONFlowErrorFailedToWriteToDisk = 4,
};

@class ONFlowResult;
@class NSError;

SWIFT_CLASS_NAMED("ONFlowResponse")
@interface ONFlowResponse : NSObject
/// The results generated upon a success run of the flow
@property (nonatomic, copy) NSArray<ONFlowResult *> * _Nullable results;
/// The error encountered during the flow if any
@property (nonatomic, strong) NSError * _Nullable error;
/// Boolean value to determine whether the flow was canceled by the user
@property (nonatomic) BOOL userCanceled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ONFlowResultType : NSInteger;

SWIFT_CLASS_NAMED("ONFlowResult")
@interface ONFlowResult : NSObject
/// The type of result
@property (nonatomic, readonly) enum ONFlowResultType type;
/// The result object (ONApplicantResult, ONDocumentResult, ONFaceResult)
@property (nonatomic, strong) id _Nonnull result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// Enumeration to list the possible results type generated during the flow
typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowResultType, "ONFlowResultType", open) {
  ONFlowResultTypeDocument = 0,
  ONFlowResultTypeFace = 1,
};


/// IdNumber object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONIdNumberResult")
@interface ONIdNumberResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSString * _Nullable stateCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PassportConfiguration")
@interface PassportConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("PhotoStepConfiguration")
@interface PhotoStepConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ResidencePermitConfiguration")
@interface ResidencePermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




































SWIFT_CLASS_NAMED("VideoStepConfiguration")
@interface VideoStepConfiguration : NSObject
- (nonnull instancetype)initWithShowIntroVideo:(BOOL)showIntroVideo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VisaConfiguration")
@interface VisaConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WorkPermitConfiguration")
@interface WorkPermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Onfido",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;

SWIFT_CLASS_NAMED("Appearance")
@interface ONAppearance : NSObject
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("secondaryBackgroundPressedColor will become unavailable.");
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor secondaryBackgroundPressedColor:(UIColor * _Nonnull)secondaryBackgroundPressedColor fontRegular:(NSString * _Nullable)fontRegular fontBold:(NSString * _Nullable)fontBold supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nonnull)primaryColor primaryTitleColor:(UIColor * _Nonnull)primaryTitleColor primaryBackgroundPressedColor:(UIColor * _Nonnull)primaryBackgroundPressedColor supportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSupportDarkMode:(BOOL)supportDarkMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Onfido25BaseDocumentConfiguration")
@interface BaseDocumentConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS_NAMED("CertificatePinningConfiguration")
@interface ONCertificatePinningConfiguration : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull hashes;
- (nullable instancetype)initWithHashes:(NSArray<NSString *> * _Nonnull)hashes error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM(NSInteger, DocumentFormat, open) {
  DocumentFormatCard = 0,
  DocumentFormatFolded = 1,
};

@class DocumentConfigBuilder;

SWIFT_CLASS_NAMED("DocumentTypeVariantConfig")
@interface ONDocumentTypeVariantConfig : NSObject
+ (DocumentConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class PassportConfiguration;
@class DrivingLicenceConfiguration;
@class NationalIdentityConfiguration;
@class ResidencePermitConfiguration;
@class VisaConfiguration;
@class WorkPermitConfiguration;
@class GenericDocumentConfiguration;

SWIFT_CLASS("_TtCC6Onfido25DocumentTypeVariantConfig21DocumentConfigBuilder")
@interface DocumentConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (DocumentConfigBuilder * _Nonnull)withPassportWithConfig:(PassportConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withDrivingLicenceWithConfig:(DrivingLicenceConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withNationalIdentityCardWithConfig:(NationalIdentityConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withResidencePermitWithConfig:(ResidencePermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withVisaWithConfig:(VisaConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withWorkPermitWithConfig:(WorkPermitConfiguration * _Nullable)config;
- (DocumentConfigBuilder * _Nonnull)withGenericWithConfig:(GenericDocumentConfiguration * _Nullable)config;
- (ONDocumentTypeVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DrivingLicenceConfiguration")
@interface DrivingLicenceConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONEnterpriseFeaturesBuilder;

SWIFT_CLASS_NAMED("EnterpriseFeatures")
@interface ONEnterpriseFeatures : NSObject
- (nonnull instancetype)initWithHideOnfidoLogo:(BOOL)hideOnfidoLogo OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use EnterpriseFeatures.builder().withHideOnfidoLogo(_:).build() instead.");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (ONEnterpriseFeaturesBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("Builder")
@interface ONEnterpriseFeaturesBuilder : NSObject
- (ONEnterpriseFeaturesBuilder * _Nonnull)withHideOnfidoLogo:(BOOL)hideOnfidoLogo;
- (ONEnterpriseFeaturesBuilder * _Nonnull)withCobrandingText:(NSString * _Nonnull)cobrandingText;
- (ONEnterpriseFeatures * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Minimal capture UI for documents and faces with built-in validation
SWIFT_CLASS("_TtC6Onfido5Event")
@interface Event : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull properties;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Builder;

SWIFT_CLASS_NAMED("FaceStepVariantConfig")
@interface ONFaceStepVariantConfig : NSObject
+ (Builder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class VideoStepConfiguration;
@class PhotoStepConfiguration;

SWIFT_CLASS("_TtCC6Onfido21FaceStepVariantConfig7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (Builder * _Nonnull)withVideoCaptureWithConfig:(VideoStepConfiguration * _Nullable)config;
- (Builder * _Nonnull)withPhotoCaptureWithConfig:(PhotoStepConfiguration * _Nullable)config;
- (ONFaceStepVariantConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("GenericDocumentConfiguration")
@interface GenericDocumentConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end






SWIFT_CLASS_NAMED("NationalIdentityConfiguration")
@interface NationalIdentityConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithDocumentFormat:(enum DocumentFormat)documentFormat country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// Address object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONAddressResult")
@interface ONAddressResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable flatNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable buildingName;
@property (nonatomic, readonly, copy) NSString * _Nullable street;
@property (nonatomic, readonly, copy) NSString * _Nullable subStreet;
@property (nonatomic, readonly, copy) NSString * _Nullable town;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSDate * _Nullable startDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class NSDate;
@class NSNumber;

SWIFT_CLASS_NAMED("ONDocumentResult")
@interface ONDocumentResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable side;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFaceResult")
@interface ONFaceResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable href;
@property (nonatomic, readonly, strong) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nullable fileName;
@property (nonatomic, readonly, copy) NSString * _Nullable fileType;
@property (nonatomic, readonly, strong) NSNumber * _Nullable fileSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfig;
@class UIViewController;
@class ONFlowResponse;

/// Objective-C wrapper for OnfidoFlow
SWIFT_CLASS_NAMED("ONFlow")
@interface ONFlow : NSObject
- (nonnull instancetype)initWithFlowConfiguration:(ONFlowConfig * _Nonnull)flowConfiguration OBJC_DESIGNATED_INITIALIZER;
- (UIViewController * _Nullable)runAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler;
- (ONFlow * _Nonnull)withResponseHandler:(void (^ _Nonnull)(ONFlowResponse * _Nonnull))responseHandler dismissFlowOnCompletion:(BOOL)dismissFlowOnCompletion;
- (ONFlow * _Nonnull)withEventHandler:(void (^ _Nonnull)(Event * _Nonnull))eventHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class ONFlowConfigBuilder;

/// Objective-C wrapper for OnfidoConfig struct
/// NOTE: Swift structs are not supported in Objective-C
SWIFT_CLASS_NAMED("ONFlowConfig")
@interface ONFlowConfig : NSObject
+ (ONFlowConfigBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ONFlowConfigBuilder")
@interface ONFlowConfigBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)withToken:(NSString * _Nonnull)token;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken;
- (void)withSdkToken:(NSString * _Nonnull)sdkToken expireHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nonnull)))expireHandler;
- (void)withApplicantId:(NSString * _Nonnull)applicantId;
- (void)withWelcomeStep;
- (void)withDocumentStep;
- (void)withDocumentStepOfType:(ONDocumentTypeVariantConfig * _Nonnull)variant;
- (void)withFaceStepOfVariant:(ONFaceStepVariantConfig * _Nonnull)variant;
- (void)withCustomLocalization;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName;
- (void)withCustomLocalizationWithTableName:(NSString * _Nonnull)tableName in:(NSBundle * _Nonnull)bundle;
- (void)withAppearance:(ONAppearance * _Nonnull)appearance;
- (void)withEnterpriseFeatures:(ONEnterpriseFeatures * _Nonnull)enterpriseFeatures;
- (void)withCertificatePinningConfiguration:(ONCertificatePinningConfiguration * _Nonnull)configuration;
/// Builds ONFlowConfig object
- (ONFlowConfig * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowConfigError, "ONFlowConfigError", open) {
  ONFlowConfigErrorMissingToken = 0,
  ONFlowConfigErrorMissingSteps = 1,
  ONFlowConfigErrorMissingApplicant = 2,
  ONFlowConfigErrorMutlipleTokenTypes = 3,
  ONFlowConfigErrorApplicantProvidedWithSDKToken = 4,
  ONFlowConfigErrorInvalidDocumentFormatAndCountryCombination = 5,
  ONFlowConfigErrorEnterpriseFeaturesNotAuthorized = 6,
  ONFlowConfigErrorSelectedEnterpriseFeatureNotAuthorized = 7,
  ONFlowConfigErrorEnterpriseFeatureProvidedWithMobileToken = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowError, "ONFlowError", open) {
  ONFlowErrorCameraPermission = 0,
  ONFlowErrorMicrophonePermission = 1,
  ONFlowErrorUpload = 2,
  ONFlowErrorException = 3,
  ONFlowErrorFailedToWriteToDisk = 4,
};

@class ONFlowResult;
@class NSError;

SWIFT_CLASS_NAMED("ONFlowResponse")
@interface ONFlowResponse : NSObject
/// The results generated upon a success run of the flow
@property (nonatomic, copy) NSArray<ONFlowResult *> * _Nullable results;
/// The error encountered during the flow if any
@property (nonatomic, strong) NSError * _Nullable error;
/// Boolean value to determine whether the flow was canceled by the user
@property (nonatomic) BOOL userCanceled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ONFlowResultType : NSInteger;

SWIFT_CLASS_NAMED("ONFlowResult")
@interface ONFlowResult : NSObject
/// The type of result
@property (nonatomic, readonly) enum ONFlowResultType type;
/// The result object (ONApplicantResult, ONDocumentResult, ONFaceResult)
@property (nonatomic, strong) id _Nonnull result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// Enumeration to list the possible results type generated during the flow
typedef SWIFT_ENUM_NAMED(NSInteger, ONFlowResultType, "ONFlowResultType", open) {
  ONFlowResultTypeDocument = 0,
  ONFlowResultTypeFace = 1,
};


/// IdNumber object as defined by the Onfido API
SWIFT_CLASS_NAMED("ONIdNumberResult")
@interface ONIdNumberResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSString * _Nullable stateCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PassportConfiguration")
@interface PassportConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("PhotoStepConfiguration")
@interface PhotoStepConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ResidencePermitConfiguration")
@interface ResidencePermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




































SWIFT_CLASS_NAMED("VideoStepConfiguration")
@interface VideoStepConfiguration : NSObject
- (nonnull instancetype)initWithShowIntroVideo:(BOOL)showIntroVideo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VisaConfiguration")
@interface VisaConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WorkPermitConfiguration")
@interface WorkPermitConfiguration : BaseDocumentConfiguration
- (nonnull instancetype)initWithCountry:(NSString * _Nonnull)country OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#endif
