source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
target 'SampleApp' do
 use_frameworks!
      
    pod 'Onfido', '18.7.0'    
  end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
