# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@bitbucket.org:onfido/onfido-pods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  # local development
  # pod 'Onfido', :path => '../'
  pod 'Onfido'
end
